version: '3.5'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: kafka-docker
    ports:
      - "9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "aerospike:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-connect:
    image: aerospike/kafka-connect-4.0
networks:
  default:
    name: kafka-connect_net
