import type { Job } from '@/api/types'

function formatJobDate(iso: string): string {
  const d = new Date(iso)
  return d.toLocaleString(undefined, {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  })
}

/**
 * Generate shell script from jobs.
 */
export function generateShellScript(jobs: Job[]): string {
  const lines: string[] = [
    '#!/bin/bash',
    '# Generated by AeroLab Web UI',
    `# Date: ${formatJobDate(new Date().toISOString())}`,
    '',
  ]
  for (const job of jobs) {
    if (job.cliCommand) {
      lines.push(`# Command: ${job.commandPath} (${formatJobDate(job.createdAt)})`)
      lines.push(job.cliCommand)
      lines.push('')
    }
  }
  return lines.join('\n')
}

/**
 * Generate markdown from jobs.
 */
export function generateMarkdown(jobs: Job[]): string {
  const lines: string[] = [
    '# AeroLab Command History',
    '',
    `*Generated: ${formatJobDate(new Date().toISOString())}*`,
    '',
  ]
  for (const job of jobs) {
    lines.push(`## ${job.commandPath}`)
    lines.push('')
    lines.push(`- **Time**: ${formatJobDate(job.createdAt)}`)
    lines.push(`- **Status**: ${job.status}`)
    if (job.cliCommand) {
      lines.push(`- **Command**: \`${job.cliCommand}\``)
    }
    const params = Object.entries(job.parameters ?? {})
      .filter(([, v]) => v !== undefined && v !== null && v !== '')
      .map(([k, v]) => `${k}=${v}`)
    if (params.length > 0) {
      lines.push(`- **Parameters**: ${params.join(', ')}`)
    }
    lines.push('')
  }
  return lines.join('\n')
}

function makeMarkdownCell(source: string[]): object {
  return { cell_type: 'markdown', metadata: {}, source }
}

function makeCodeCell(source: string[]): object {
  return {
    cell_type: 'code',
    metadata: {},
    source,
    outputs: [],
    execution_count: null,
  }
}

/**
 * Generate Jupyter notebook with bash kernel.
 */
export function generateJupyterBash(jobs: Job[]): string {
  const cells: object[] = []
  cells.push(
    makeMarkdownCell([
      '# AeroLab Command History (Bash)\n',
      `# Generated: ${formatJobDate(new Date().toISOString())}`,
    ])
  )
  for (const job of jobs) {
    if (job.cliCommand) {
      cells.push(
        makeCodeCell([`# ${job.commandPath} (${formatJobDate(job.createdAt)})\n`, job.cliCommand])
      )
    }
  }
  const nb = {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: {
        display_name: 'Bash',
        language: 'bash',
        name: 'bash',
      },
      language_info: {
        name: 'bash',
      },
    },
    cells,
  }
  return JSON.stringify(nb, null, 2)
}

/**
 * Generate Jupyter notebook with Python kernel (subprocess).
 */
export function generateJupyterPython(jobs: Job[]): string {
  const cells: object[] = []
  cells.push(
    makeMarkdownCell([
      '# AeroLab Command History (Python)\n',
      `# Generated: ${formatJobDate(new Date().toISOString())}\n`,
      'Run each cell to execute the aerolab command via subprocess.',
    ])
  )
  for (const job of jobs) {
    if (job.cliCommand) {
      const parts = job.cliCommand.split(/\s+/).filter(Boolean)
      const cmd = parts[0] === 'aerolab' ? parts : ['aerolab', ...parts]
      const escaped = cmd.map((s) => JSON.stringify(s)).join(', ')
      cells.push(
        makeCodeCell([
          `# ${job.commandPath} (${formatJobDate(job.createdAt)})\n`,
          `import subprocess\n`,
          `subprocess.run([${escaped}], check=True)`,
        ])
      )
    }
  }
  const nb = {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: {
        display_name: 'Python 3',
        language: 'python',
        name: 'python3',
      },
      language_info: {
        name: 'python',
        version: '3',
      },
    },
    cells,
  }
  return JSON.stringify(nb, null, 2)
}

/**
 * Trigger browser download of content as a file.
 */
export function downloadBlob(
  content: string,
  filename: string,
  mimeType: string
): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
