import {
  Server,
  Monitor,
  Network,
  HardDrive,
  Settings,
  Key,
  Lock,
  Upload,
  Download,
  FileText,
  Folder,
  Terminal,
  List,
  RefreshCw,
  Play,
  Square,
  Trash2,
  Plus,
  BarChart3,
  Database,
  Cloud,
  Shield,
  Clock,
  Wrench,
  Code,
  Eye,
  PlusCircle,
  MinusCircle,
  ArrowUpCircle,
  Info,
  HelpCircle,
  GitBranch,
  Copy,
  Link,
  ListOrdered,
  Search,
  Minus,
  Pencil,
  PenSquare,
  Plug,
  LogIn,
  RotateCw,
  Share2,
  SlidersHorizontal,
  Tag,
  Tags,
  Table,
  Layers,
  Flame,
  FlaskConical,
  Box,
  Maximize2,
  GripHorizontal,
  Hammer,
  Headphones,
  Hourglass,
  BadgeCheck,
  UserX,
  Warehouse,
  TrendingUp,
  Calendar,
  Eraser,
  ShieldCheck,
  SkipForward,
  Globe,
  Gauge,
  FolderOpen,
  FileCode,
  FileImage,
  FileOutput,
  Workflow,
  MessageSquare,
  Zap,
  ArrowRight,
  LayoutGrid,
  type LucideIcon,
} from 'lucide-react'

/**
 * Maps FontAwesome-style icon class strings (from Go webicon struct tags)
 * to Lucide React icon components.
 *
 * Each FA icon is mapped with both "fas fa-xxx" and bare "fa-xxx" forms
 * so the fallback logic in getIcon() can match either.
 */
const iconMap: Record<string, LucideIcon> = {
  // --- Already had mappings ---
  'fas fa-server': Server,
  'fa-server': Server,
  'fas fa-desktop': Monitor,
  'fa-desktop': Monitor,
  'fas fa-network-wired': Network,
  'fa-network-wired': Network,
  'fas fa-hdd': HardDrive,
  'fa-hdd': HardDrive,
  'fas fa-cog': Settings,
  'fa-cog': Settings,
  'fas fa-cogs': Settings,
  'fa-cogs': Settings,
  'fas fa-key': Key,
  'fa-key': Key,
  'fas fa-lock': Lock,
  'fa-lock': Lock,
  'fas fa-upload': Upload,
  'fa-upload': Upload,
  'fas fa-download': Download,
  'fa-download': Download,
  'fas fa-file': FileText,
  'fa-file': FileText,
  'fas fa-folder': Folder,
  'fa-folder': Folder,
  'fas fa-terminal': Terminal,
  'fa-terminal': Terminal,
  'fas fa-list': List,
  'fa-list': List,
  'fas fa-sync': RefreshCw,
  'fa-sync': RefreshCw,
  'fas fa-play': Play,
  'fa-play': Play,
  'fas fa-stop': Square,
  'fa-stop': Square,
  'fas fa-trash': Trash2,
  'fa-trash': Trash2,
  'fas fa-plus': Plus,
  'fa-plus': Plus,
  'fas fa-chart-bar': BarChart3,
  'fa-chart-bar': BarChart3,
  'fas fa-database': Database,
  'fa-database': Database,
  'fas fa-cloud': Cloud,
  'fa-cloud': Cloud,
  'fas fa-shield-alt': Shield,
  'fa-shield-alt': Shield,
  'fas fa-clock': Clock,
  'fa-clock': Clock,
  'fas fa-tools': Wrench,
  'fa-tools': Wrench,
  'fas fa-code': Code,
  'fa-code': Code,
  'fas fa-eye': Eye,
  'fa-eye': Eye,

  // --- New mappings for icons used in command structs ---

  // Aerospike daemon controls
  'fas fa-a': Zap,
  'fa-a': Zap,

  // Config / settings
  'fas fa-toolbox': Wrench,
  'fa-toolbox': Wrench,
  'fas fa-gear': Settings,
  'fa-gear': Settings,
  'fas fa-gears': Settings,
  'fa-gears': Settings,
  'fas fa-vials': FlaskConical,
  'fa-vials': FlaskConical,
  'fas fa-arrow-right-to-city': ArrowRight,
  'fa-arrow-right-to-city': ArrowRight,
  'fas fa-wrench': Wrench,
  'fa-wrench': Wrench,
  'fas fa-screwdriver': Wrench,
  'fa-screwdriver': Wrench,

  // Create / add
  'fas fa-circle-plus': PlusCircle,
  'fa-circle-plus': PlusCircle,

  // Remove / delete / minus
  'fas fa-circle-minus': MinusCircle,
  'fa-circle-minus': MinusCircle,
  'fas fa-minus': Minus,
  'fa-minus': Minus,
  'fas fa-square-minus': MinusCircle,
  'fa-square-minus': MinusCircle,
  'fas fa-trash-can': Trash2,
  'fa-trash-can': Trash2,
  'fas fa-dumpster': Trash2,
  'fa-dumpster': Trash2,
  'fas fa-user-xmark': UserX,
  'fa-user-xmark': UserX,

  // Upgrade / version
  'fas fa-circle-arrow-up': ArrowUpCircle,
  'fa-circle-arrow-up': ArrowUpCircle,
  'fas fa-code-branch': GitBranch,
  'fa-code-branch': GitBranch,

  // Info / help
  'fas fa-info': Info,
  'fa-info': Info,
  'fas fa-info-circle': Info,
  'fa-info-circle': Info,
  'fas fa-circle-info': Info,
  'fa-circle-info': Info,
  'fas fa-circle-question': HelpCircle,
  'fa-circle-question': HelpCircle,

  // Files
  'fas fa-file-alt': FileText,
  'fa-file-alt': FileText,
  'fas fa-file-code': FileCode,
  'fa-file-code': FileCode,
  'fas fa-file-export': FileOutput,
  'fa-file-export': FileOutput,
  'fas fa-file-image': FileImage,
  'fa-file-image': FileImage,
  'fas fa-folder-open': FolderOpen,
  'fa-folder-open': FolderOpen,
  'fas fa-folder-tree': Folder,
  'fa-folder-tree': Folder,

  // Network / connectivity
  'fas fa-plug': Plug,
  'fa-plug': Plug,
  'fas fa-link': Link,
  'fa-link': Link,
  'fas fa-globe': Globe,
  'fa-globe': Globe,
  'fas fa-share': Share2,
  'fa-share': Share2,
  'fas fa-firewall': Shield,
  'fa-firewall': Shield,

  // Monitoring / charts
  'fas fa-chart-line': TrendingUp,
  'fa-chart-line': TrendingUp,
  'fas fa-bars-progress': BarChart3,
  'fa-bars-progress': BarChart3,
  'fas fa-gauge': Gauge,
  'fa-gauge': Gauge,
  'fas fa-tachograph-digital': Gauge,
  'fa-tachograph-digital': Gauge,

  // Edit / modify
  'fas fa-pencil': Pencil,
  'fa-pencil': Pencil,
  'fas fa-pen-to-square': PenSquare,
  'fa-pen-to-square': PenSquare,

  // Copy
  'fas fa-copy': Copy,
  'fa-copy': Copy,

  // Misc actions
  'fas fa-rotate': RotateCw,
  'fa-rotate': RotateCw,
  'fas fa-expand': Maximize2,
  'fa-expand': Maximize2,
  'fas fa-forward-step': SkipForward,
  'fa-forward-step': SkipForward,
  'fas fa-right-to-bracket': LogIn,
  'fa-right-to-bracket': LogIn,
  'fas fa-magnifying-glass': Search,
  'fa-magnifying-glass': Search,
  'fas fa-broom': Eraser,
  'fa-broom': Eraser,
  'fas fa-hammer': Hammer,
  'fa-hammer': Hammer,

  // Layout / grouping
  'fas fa-sliders': SlidersHorizontal,
  'fa-sliders': SlidersHorizontal,
  'fas fa-layer-group': Layers,
  'fa-layer-group': Layers,
  'fas fa-object-group': LayoutGrid,
  'fa-object-group': LayoutGrid,
  'fas fa-diagram-project': Workflow,
  'fa-diagram-project': Workflow,
  'fas fa-grip-lines': GripHorizontal,
  'fa-grip-lines': GripHorizontal,
  'fas fa-table-list': Table,
  'fa-table-list': Table,

  // Tags
  'fas fa-tag': Tag,
  'fa-tag': Tag,
  'fas fa-tags': Tags,
  'fa-tags': Tags,

  // Lists
  'fas fa-list-ol': ListOrdered,
  'fa-list-ol': ListOrdered,

  // Infrastructure
  'fas fa-warehouse': Warehouse,
  'fa-warehouse': Warehouse,
  'fas fa-hard-drive': HardDrive,
  'fa-hard-drive': HardDrive,
  'fas fa-tv': Monitor,
  'fa-tv': Monitor,
  'fas fa-sd-card': HardDrive,
  'fa-sd-card': HardDrive,

  // Security
  'fas fa-building-shield': ShieldCheck,
  'fa-building-shield': ShieldCheck,
  'fas fa-passport': BadgeCheck,
  'fa-passport': BadgeCheck,
  'fas fa-id-badge': BadgeCheck,
  'fa-id-badge': BadgeCheck,
  'fas fa-unlock': Lock,
  'fa-unlock': Lock,

  // Time
  'fas fa-hourglass': Hourglass,
  'fa-hourglass': Hourglass,
  'fas fa-calendar-alt': Calendar,
  'fa-calendar-alt': Calendar,

  // Other
  'fas fa-fire': Flame,
  'fa-fire': Flame,
  'fas fa-flask': FlaskConical,
  'fa-flask': FlaskConical,
  'fas fa-box-open': Box,
  'fa-box-open': Box,
  'fas fa-comment': MessageSquare,
  'fa-comment': MessageSquare,
  'fas fa-headphones': Headphones,
  'fa-headphones': Headphones,
  'fas fa-divide': Minus,
  'fa-divide': Minus,
  'fas fa-tent': Server,
  'fa-tent': Server,
  'fas fa-tents': Server,
  'fa-tents': Server,
  'fas fa-arrows-turn-to-dots': Workflow,
  'fa-arrows-turn-to-dots': Workflow,

  // Brand icons (no brand-specific icons in Lucide, use reasonable substitutes)
  'fa-brands fa-aws': Cloud,
  'fa-brands fa-docker': Box,
  'fa-brands fa-google': Cloud,
  'fa-brands fa-warehouse': Warehouse,
}

const defaultIcon = Settings

export function getIcon(faClass: string): LucideIcon {
  if (!faClass) return defaultIcon
  if (iconMap[faClass]) return iconMap[faClass]
  const parts = faClass.split(' ')
  for (const part of parts) {
    if (iconMap[part]) return iconMap[part]
    if (iconMap[`fas ${part}`]) return iconMap[`fas ${part}`]
  }
  return defaultIcon
}
