package baws

const (
	TAG_NAME            = "Name"
	TAG_DESCRIPTION     = "Description"
	TAG_AEROLAB_VERSION = "AEROLAB_VERSION"
	TAG_AEROLAB_PROJECT = "AEROLAB_PROJECT"
	TAG_OWNER           = "AEROLAB_OWNER"
	TAG_EXPIRES         = "AEROLAB_EXPIRES"
	TAG_CLUSTER_NAME    = "AEROLAB_CLUSTER_NAME"
	TAG_NODE_NO         = "AEROLAB_NODE_NO"
	TAG_OS_NAME         = "AEROLAB_OS_NAME"
	TAG_OS_VERSION      = "AEROLAB_OS_VERSION"
	TAG_COST_PPH        = "AEROLAB_COST_PPH"
	TAG_COST_SO_FAR     = "AEROLAB_COST_SO_FAR"
	TAG_COST_GB         = "AEROLAB_COST_PER_GB"
	TAG_START_TIME      = "AEROLAB_LAST_START_TIME"
	TAG_DNS_NAME        = "AEROLAB_DNS_NAME"
	TAG_DNS_DOMAIN_ID   = "AEROLAB_DNS_DOMAIN_ID"
	TAG_DNS_DOMAIN_NAME = "AEROLAB_DNS_DOMAIN_NAME"
	TAG_DNS_REGION      = "AEROLAB_DNS_REGION"
	TAG_CLUSTER_UUID    = "AEROLAB_CLUSTER_UUID"
)
