package bvagrant

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

// vagrantfileTemplateSrc renders the per-cluster Vagrantfile. Every node gets provider
// blocks for all four supported providers; the provider actually used is selected at
// `vagrant up` time via --provider, not baked into the file.
const vagrantfileTemplateSrc = `# This file is generated by aerolab. Do not edit; it is regenerated
# whenever the cluster's nodes change.
Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 600
{{- range .Nodes }}

  config.vm.define "{{ .MachineName }}" do |node|
    node.vm.box = "{{ .Box }}"
    node.vm.hostname = "{{ .MachineName }}"
    node.vm.network "private_network", ip: "{{ .IP }}"
{{- range .SyncedFolders }}
    node.vm.synced_folder "{{ .Host }}", "{{ .Guest }}"{{ if .ReadOnly }}, mount_options: ["ro"]{{ end }}
{{- end }}

    node.vm.provider "virtualbox" do |vb|
      vb.memory = {{ .RAMMB }}
      vb.cpus = {{ .CPUs }}
      vb.name = "{{ .MachineName }}"
    end

    node.vm.provider "libvirt" do |lv|
      lv.memory = {{ .RAMMB }}
      lv.cpus = {{ .CPUs }}
    end

    node.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = "{{ .RAMMB }}"
      v.vmx["numvcpus"] = "{{ .CPUs }}"
    end

    node.vm.provider "hyperv" do |hv|
      hv.memory = {{ .RAMMB }}
      hv.cpus = {{ .CPUs }}
      hv.vmname = "{{ .MachineName }}"
    end

    node.vm.provision "shell", inline: <<-SHELL
      set -e
      mkdir -p /root/.ssh
      chmod 700 /root/.ssh
      touch /root/.ssh/authorized_keys
      grep -qF "{{ $.PubKey }}" /root/.ssh/authorized_keys || echo "{{ $.PubKey }}" >> /root/.ssh/authorized_keys
      chmod 600 /root/.ssh/authorized_keys
      if [ -d /etc/ssh/sshd_config.d ]; then
        echo "PermitRootLogin prohibit-password" > /etc/ssh/sshd_config.d/60-aerolab.conf
      else
        sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config
      fi
      systemctl reload sshd || systemctl reload ssh || service ssh reload || true
      VAGRANT_UID=$(id -u vagrant 2>/dev/null || echo "")
      if [ -n "$VAGRANT_UID" ]; then
        VAGRANT_HOME=$(getent passwd vagrant | cut -d: -f6)
        mkdir -p "$VAGRANT_HOME/.ssh"
        chmod 700 "$VAGRANT_HOME/.ssh"
        touch "$VAGRANT_HOME/.ssh/authorized_keys"
        grep -qF "{{ $.PubKey }}" "$VAGRANT_HOME/.ssh/authorized_keys" || echo "{{ $.PubKey }}" >> "$VAGRANT_HOME/.ssh/authorized_keys"
        chmod 600 "$VAGRANT_HOME/.ssh/authorized_keys"
        chown -R vagrant:vagrant "$VAGRANT_HOME/.ssh" || true
      fi
    SHELL
  end
{{- end }}
end
`

var vagrantfileTemplate = template.Must(template.New("Vagrantfile").Parse(vagrantfileTemplateSrc))

// vfSyncedFolder is a single synced_folder line derived from a nodeMeta.Disks entry.
type vfSyncedFolder struct {
	Host     string
	Guest    string
	ReadOnly bool
}

// vfNode is the per-node template data for renderVagrantfile.
type vfNode struct {
	MachineName   string
	Box           string
	IP            string
	CPUs          int
	RAMMB         int
	SyncedFolders []vfSyncedFolder
}

// vfData is the top-level template data for renderVagrantfile.
type vfData struct {
	Nodes  []vfNode
	PubKey string
}

const (
	defaultVagrantCPUs  = 2
	defaultVagrantRAMMB = 2048
)

// renderVagrantfile renders the Vagrantfile content for a cluster's current metadata.
// Nodes are iterated in ascending node-number order so the output is deterministic
// regardless of Go's randomized map iteration order.
func (s *b) renderVagrantfile(meta *clusterMeta, pubKey string) (string, error) {
	if meta == nil {
		return "", fmt.Errorf("cannot render Vagrantfile: nil cluster metadata")
	}

	nodeNos := make([]int, 0, len(meta.Nodes))
	for no := range meta.Nodes {
		nodeNos = append(nodeNos, no)
	}
	sort.Ints(nodeNos)

	data := vfData{PubKey: strings.TrimSpace(pubKey)}
	for _, no := range nodeNos {
		node := meta.Nodes[no]
		if node == nil {
			continue
		}
		folders, err := s.parseSyncedFolders(node.Disks)
		if err != nil {
			return "", fmt.Errorf("node %d (%s): %w", no, node.MachineName, err)
		}

		cpus := node.CPUs
		if cpus <= 0 {
			cpus = defaultVagrantCPUs
		}
		ram := node.RAMMB
		if ram <= 0 {
			ram = defaultVagrantRAMMB
		}

		data.Nodes = append(data.Nodes, vfNode{
			MachineName:   node.MachineName,
			Box:           node.Box,
			IP:            node.IP,
			CPUs:          cpus,
			RAMMB:         ram,
			SyncedFolders: folders,
		})
	}

	var buf bytes.Buffer
	if err := vagrantfileTemplate.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// parseSyncedFolders parses nodeMeta.Disks entries of the form
// "volumeName:/guest/path" or "volumeName:/guest/path:ro" into synced_folder
// definitions rooted at <configDir>/volumes/<volumeName>. Malformed entries are an error.
func (s *b) parseSyncedFolders(disks []string) ([]vfSyncedFolder, error) {
	folders := make([]vfSyncedFolder, 0, len(disks))
	for _, d := range disks {
		parts := strings.Split(d, ":")

		var volume, guest string
		readOnly := false

		switch len(parts) {
		case 2:
			volume, guest = parts[0], parts[1]
		case 3:
			if parts[2] != "ro" {
				return nil, fmt.Errorf("malformed disk entry %q: unknown suffix %q (expected \"ro\")", d, parts[2])
			}
			volume, guest = parts[0], parts[1]
			readOnly = true
		default:
			return nil, fmt.Errorf("malformed disk entry %q: expected volumeName:/guest/path[:ro]", d)
		}

		if volume == "" {
			return nil, fmt.Errorf("malformed disk entry %q: empty volume name", d)
		}
		if guest == "" || !strings.HasPrefix(guest, "/") {
			return nil, fmt.Errorf("malformed disk entry %q: guest path must be a non-empty absolute path", d)
		}

		folders = append(folders, vfSyncedFolder{
			Host:     filepath.Join(s.configDir, "volumes", volume),
			Guest:    guest,
			ReadOnly: readOnly,
		})
	}
	return folders, nil
}

// writeVagrantfile renders and writes the Vagrantfile for a cluster to
// <clusterDir>/Vagrantfile, overwriting any existing file (e.g. after node changes).
func (s *b) writeVagrantfile(meta *clusterMeta, pubKey string) error {
	if meta == nil {
		return fmt.Errorf("cannot write Vagrantfile: nil cluster metadata")
	}
	content, err := s.renderVagrantfile(meta, pubKey)
	if err != nil {
		return err
	}
	dir := s.clusterDir(meta.ClusterName)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "Vagrantfile"), []byte(content), 0644)
}
