# see https://github.com/eksctl-io/eksctl/tree/main/examples for official eksctl examples
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: testCluster
  region: {AWS-REGION}
  tags:
    initialExpiry: 30h # provide `eksexpiry` tool to change expiry: eksexpiry --name bobCluster --region {AWS-REGION} --in 30h

iam:
  withOIDC: true
  serviceAccounts:
  # Basic items
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: external-dns
      namespace: kube-system
    wellKnownPolicies:
      externalDNS: true
  - metadata:
      name: cert-manager
      namespace: cert-manager
    wellKnownPolicies:
      certManager: true
  # Load Balancer item
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  # Autoscaler
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    wellKnownPolicies:
      autoScaler: true
  # Autoscaler
  - metadata:
      name: autoscaler-service
      namespace: kube-system
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        - "ec2:DescribeLaunchTemplateVersions"
        Resource: '*'

nodeGroups: # to define more nodegroups, copy-paste the below definition block, change name, and optionally availability zone and taints/labels
  - name: testNodeGroup1
    availabilityZones: ["{AWS-REGION}a"]
    instanceType: r5a.2xlarge
    volumeSize: 100
    volumeType: gp2
    ssh: # import default public key (~/.ssh/id_rsa.pub)
      allow: true
    desiredCapacity: 4
    minSize: 4 # for ease of use minSize==desiredCapacity
    maxSize: 8
    iam:
      withAddonPolicies:
        ebs: true
        autoScaler: true # autoscaler
    tags: # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-13: "owned"
    classicLoadBalancerNames: # load balancer
      - ng3-classic-load-balancer
    # OPTIONAL: auto-applied taints
    #taints:
    #  - key: special
    #    value: "true"
    #    effect: NoSchedule
    # OPTIONAL: auto-applied labels
    #labels:
    #  labelName: labelValue

# specifcy all AZs where nodeGroups live; if using just ONE, specify 2 here, one unused (for some weird reason)
availabilityZones: ["{AWS-REGION}a","{AWS-REGION}b"]

addons:
- name: vpc-cni
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest
- name: kube-proxy
  version: latest
- name: aws-ebs-csi-driver
  wellKnownPolicies:
    ebsCSIController: true
