# Aerospike Graph Configuration
# Generated by AeroLab

# Aerospike connection settings
aerospike.client.host={{ range $i, $seed := .Seeds }}{{ if $i }},{{ end }}{{ $seed }}{{ end }}
aerospike.client.namespace={{ .Namespace }}

# Graph server settings
gremlin.graph=org.apache.tinkerpop.gremlin.aerospike.AerospikeGraph
gremlin.graph.aerospike.namespace={{ .Namespace }}

{{ if gt .RAMMb 0 }}
# Memory settings
# Note: JVM heap size should be configured via JAVA_OPTS environment variable
# Recommended: -Xmx{{ .RAMMb }}m -Xms{{ .RAMMb }}m
{{ end }}

# Extra properties
{{ range .ExtraProperties }}
{{ . }}
{{ end }}

