#!/bin/bash
# Aerospike Graph Installation Script
# Generated by AeroLab

set -e

echo "=== Installing Aerospike Graph ==="

# Install Docker if not present
if ! command -v docker &> /dev/null; then
    echo "Docker not found, installing..."
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    bash /tmp/get-docker.sh
    systemctl enable docker
    systemctl start docker
    echo "Docker installed successfully"
fi

# Wait for Docker to be ready
echo "Waiting for Docker to be ready..."
timeout=60
while ! docker info &>/dev/null; do
    sleep 1
    timeout=$((timeout - 1))
    if [ $timeout -le 0 ]; then
        echo "ERROR: Docker failed to start"
        exit 1
    fi
done
echo "Docker is ready"

{{ if and .DockerLoginUser .DockerLoginPass }}
# Docker registry login
echo "Logging in to Docker registry..."
{{ if .DockerLoginURL }}
docker login --username "{{ .DockerLoginUser }}" --password "{{ .DockerLoginPass }}" "{{ .DockerLoginURL }}"
{{ else }}
docker login --username "{{ .DockerLoginUser }}" --password "{{ .DockerLoginPass }}"
{{ end }}
{{ end }}

# Pull the graph image
echo "Pulling Aerospike Graph image: {{ .GraphImage }}"
docker pull "{{ .GraphImage }}"

# Stop and remove existing graph container if any
echo "Stopping any existing graph container..."
docker stop aerospike-graph 2>/dev/null || true
docker rm aerospike-graph 2>/dev/null || true

# Run the graph container
echo "Starting Aerospike Graph container..."
docker run -d \
    --name aerospike-graph \
    --restart unless-stopped \
    -p 8182:8182 \
{{ if .GraphPrivileged }}    --privileged \
{{ end }}    -v "{{ .ConfigPath }}:/opt/aerospike-graph/aerospike-graph.properties:ro" \
    "{{ .GraphImage }}"

# Wait for graph to be ready
echo "Waiting for Aerospike Graph to start..."
timeout=120
while ! docker logs aerospike-graph 2>&1 | grep -q "GremlinServer started"; do
    sleep 2
    timeout=$((timeout - 2))
    if [ $timeout -le 0 ]; then
        echo "WARNING: Graph server may not have started within timeout, check logs:"
        docker logs aerospike-graph
        break
    fi
    
    # Check if container is still running
    if ! docker ps -q -f name=aerospike-graph | grep -q .; then
        echo "ERROR: Graph container stopped unexpectedly. Logs:"
        docker logs aerospike-graph
        exit 1
    fi
done

echo "=== Aerospike Graph installation complete ==="
echo "Graph server is running on port 8182"
echo "To view logs: docker logs -f aerospike-graph"
echo "To connect: gremlin-console and use ':remote connect tinkerpop.server conf/remote.yaml'"

