service:
  port: 8080
 
producer-props:
  bootstrap.servers:
  - kafka:9092
 
logging:
  file: /var/log/aerospike-kafka-outbound/aerospike-kafka-outbound.log
 
format:
  mode: json
 
routing:
  mode: static
  destination: aerospike
