openapi: 3.0.0
info:
  title: Aerospike Cloud Public API
  version: 1.0.0
  description: Public API for the Aerospike Cloud offering
  contact:
    name: Aerospike Cloud
  x-logo:
    url: https://console.aerospike.com/static/aerospike-logo.svg
    altText: Aerospike Logo
servers:
  - url: https://api.aerospike.com/v1
security:
  - publicOauth2: []
tags:
  - name: cluster
    x-displayName: Clusters
    description: |
      APIs which facilitate cluster management as a service.
  - name: cluster-credential
    x-displayName: Credentials
    description: |
      APIs which facilitate api-key management.
  - name: cluster-vpc-peering
    x-displayName: VPC Peerings
    description: |
      APIs which facilitate VPC peering management.
  - name: organization
    x-displayName: Organization
    description: |
      APIs which facilitate self service organization management
  - name: secret
    x-displayName: Secrets
    description: |
      APIs which facilitate secret management.
  - name: api-key
    x-displayName: API Keys
    description: |
      APIs for managing API keys.
  - name: cloud-provider
    x-displayName: Cloud Providers
    description: |
      APIs which facilitate cloud-provider actions.
paths:
  /organization:
    get:
      summary: Get your organization
      description: Get your organization
      security:
        - publicOauth2:
            - read:org
      tags:
        - organization
      operationId: getOrganization
  /organization/members:
    get:
      summary: List org members
      description: List members of the organization.
      security:
        - publicOauth2:
            - read:org
      tags:
        - organization
      operationId: listOrgMembers
  /organization/members/{userId}:
    delete:
      summary: Remove org member
      description: Removes a member from the organization.
      security:
        - publicOauth2:
            - update:org
      tags:
        - organization
      operationId: removeOrgMember
  /api-keys:
    get:
      summary: List API keys.
      description: List API keys.
      security:
        - publicOauth2:
            - read:api-key
      tags:
        - api-key
      operationId: listApiKeys
    post:
      summary: Create a new API key
      description: Create a new API key
      security:
        - publicOauth2:
            - create:api-key
      tags:
        - api-key
      operationId: createApiKey
  /api-keys/{clientId}:
    delete:
      summary: Delete an API key
      description: Delete an API key
      security:
        - publicOauth2:
            - delete:api-key
      tags:
        - api-key
      operationId: deleteApiKey
  /secrets:
    get:
      summary: List all secrets.
      description: Retrieves a list of all secrets accessible to the user
      security:
        - publicOauth2:
            - read:secret
      tags:
        - secret
      operationId: listSecrets
    post:
      summary: Create a new secret
      description: Create a new secret
      security:
        - publicOauth2:
            - create:secret
      tags:
        - secret
      operationId: createSecret
  /secrets/{secretId}:
    get:
      description: Get an existing secret by Id
      security:
        - publicOauth2:
            - read:secret
      tags:
        - secret
      summary: Get an existing secret
      operationId: getSecretById
    delete:
      summary: Delete a secret
      description: Delete a secret.
      security:
        - publicOauth2:
            - delete:secret
      tags:
        - secret
      operationId: deleteSecretById
  /database/cloud-providers:
    get:
      summary: List supported cloud providers.
      description: |
        Returns a list of supported cloud providers and regions.
      security:
        - publicOauth2: []
      tags:
        - cloud-provider
      operationId: getCloudProviders
  /database/cloud-providers/{cloudProviderId}/instance-types/{instanceTypeId}:
    get:
      summary: Get specs for an instance type.
      description: Returns the specs for a given instance type.
      security:
        - publicOauth2: []
      tags:
        - cloud-provider
      operationId: getCloudProviderInstanceTypeSpecs
  /database/clusters:
    get:
      summary: List clusters.
      description: |-
        Retrieves a list of all clusters accessible to the user.
        The list can be filtered by status.
      security:
        - publicOauth2:
            - read:database
      tags:
        - cluster
      operationId: listClusters
    post:
      summary: Create a new cluster
      description: Create a new cluster
      security:
        - publicOauth2:
            - create:database
      tags:
        - cluster
      operationId: createCluster
  /database/clusters/{clusterId}:
    get:
      description: Get an existing database by Id
      security:
        - publicOauth2:
            - read:database
      tags:
        - cluster
      summary: Get an existing database
      operationId: getClusterById
    patch:
      summary: Update an existing cluster
      description: Update an existing cluster.
      security:
        - publicOauth2:
            - update:database
      tags:
        - cluster
      operationId: updateClusterById
    delete:
      summary: Delete a cluster
      description: Delete a cluster.
      security:
        - publicOauth2:
            - delete:database
      tags:
        - cluster
      operationId: deleteClusterById
  /database/clusters/{clusterId}/metrics:
    get:
      summary: Get cluster metrics
      description: Returns all metrics for the given cluster
      security:
        - publicOauth2:
            - read:database
      tags:
        - cluster
      operationId: getClusterMetrics
  /database/clusters/{clusterId}/credentials:
    get:
      summary: List credentials for a cluster
      description: List credentials for a clusters.
      security:
        - publicOauth2:
            - read:database
      tags:
        - cluster-credential
      operationId: getClusterCredentials
    post:
      summary: Create new credentials for a database
      description: |
        Create a new API key for a database.

        Supports `read`, `write`, `read-write` privileges for CORE databases. Defaults to `read-write`.
      security:
        - publicOauth2:
            - update:database
      tags:
        - cluster-credential
      operationId: createClusterCredentials
  /database/clusters/{clusterId}/credentials/{credentialsId}:
    delete:
      summary: Delete credentials for a cluster
      description: Deletes credentials for a cluster.
      security:
        - publicOauth2:
            - update:database
      tags:
        - cluster-credential
      operationId: deleteClusterCredentialsById
  /database/clusters/{clusterId}/private-access:
  /database/clusters/{clusterId}/private-access/consumers:
  /database/clusters/{clusterId}/private-access/consumers/{consumerId}:
  /database/clusters/{clusterId}/vpc-peerings:
    post:
      summary: Create a single VPC Peering connection for the cluster
      description: Create a single VPC Peering connection for the cluster.
      security:
        - publicOauth2:
            - update:database
      tags:
        - cluster-vpc-peering
      operationId: createVPCPeerings
    get:
      summary: List VPC peering information
      description: List VPC peering information
      security:
        - publicOauth2:
            - read:database
      tags:
        - cluster-vpc-peering
      operationId: getVPCPeerings
  /database/clusters/{clusterId}/vpc-peerings/{peeringId}:
    delete:
      summary: Delete a VPC peering connection
      description: Delete a VPC peering connection.
      security:
        - publicOauth2:
            - delete:database
      tags:
        - cluster-vpc-peering
      operationId: deleteVPCPeerings
  /pricing/rates/{region_id}:
    get:
      summary: Get pricing rates
      description: |
        Returns pricing rates for all machine types organized by machine type for a specific region.
      operationId: getPricingRates
      tags:
        - pricing
      security:
        - publicOauth2:
            - read:database
components:
  securitySchemes:
    publicOauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.control.aerospike.cloud/oauth/token
          scopes:
            read:database: Read operations on cluster resources
            update:database: Update operations on cluster resources
            create:database: Create operations on cluster resources
            delete:database: Delete operations on cluster resources
            read:org: Read operations on org resources
            update:org: Update operations on org resources
            read:api-key: Read operations on environment resources
            create:api-key: Create operations on api key resources
            delete:api-key: Delete operations on api key resources
            read:secret: Read operations on secret resources
            create:secret: Create operations on secret resources
            delete:secret: Delete operations on secret resources
x-cli-config:
  security: publicOauth2
  prompt:
    client_id:
      description: API Key ID
    client_secret:
      description: API Key secret
  params:
    client_id: '{client_id}'
    client_secret: '{client_secret}'
x-tagGroups:
  - name: Access Management
    tags:
      - organization
      - user
      - secret
      - api-key
  - name: Database
    tags:
      - cloud-provider
      - cluster
      - cluster-credential
      - cluster-private-access
      - cluster-vpc-peering
      - pricing
