version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    #- dupl
    - errcheck
    #- goconst
    #- gosec
    - govet
    - ineffassign
    - misspell
    - predeclared
    - staticcheck
    - unconvert
    #- unparam
  settings:
    gosec:
      excludes:
        - G104
        - G115
        - G117
    errcheck:
      exclude-functions:
        - (*github.com/aerospike/aerolab/pkg/backend/backends.Architecture).FromString
        - (github.com/aerospike/aerolab/pkg/backend/backends.Backend).ForceRefreshInventory
        - (github.com/rglonek/aerospike-config-file-parser.Stanza).SetValue
        - (github.com/rglonek/aerospike-config-file-parser.Stanza).SetValues
        - (github.com/rglonek/aerospike-config-file-parser.Stanza).Delete
        - (github.com/rglonek/aerospike-config-file-parser.Stanza).NewStanza
        - os.Remove
        - os.RemoveAll
        - os.Setenv
        - os.Unsetenv
  exclusions:
    rules:
      - linters:
          - errcheck
        source: "defer s.invalidateCacheFunc"
      - linters:
          - errcheck
        source: "PrintHelp"
      - linters:
          - errcheck
        source: '\.Close\(\)'
      - linters:
          - errcheck
        source: 'c\.Help\.Execute\(args\)'
      - linters:
          - errcheck
        source: 'UpdateJobStatus'
      - linters:
          - errcheck
        source: 'wsWrite\('
