package main

var E_HELP = 1
var E_MAIN_LOGGER = 2
var E_MAIN_CMDLINEPARAMS = 3
var E_MAIN_CONFIG = 4
var E_MAKECLUSTER_VALIDATION = int64(5)
var E_BACKEND_ERROR = int64(6)
var E_MAKECLUSTER_READFILE = int64(7)
var E_MAKECLUSTER_NODEIPS = int64(8)
var E_MAKECLUSTER_NODELIST = int64(9)
var E_MAKECLUSTER_READCONF = int64(10)
var E_MAKECLUSTER_FIXCONF = int64(11)
var E_MAKECLUSTER_READFEATURES = int64(12)
var E_MAKECLUSTER_COPYFILES = int64(13)
var E_MAKECLUSTER_START = int64(14)
var E_INTERACTIVE = int64(15)
var E_MAKECLUSTER_MAKECLUSTER = int64(16)
var E_MAKECLUSTER_MAKETEMPLATE = int64(17)
