if [ "$1" != "-fix" ]; then
    PARAM="-diff"
    echo "Running go fix on all platforms with -diff (dryrun mode), run with '-fix' to actually fix the issues"
else
    PARAM=""
    echo "Running go fix on all platforms (real mode)"
fi

GOOS=linux GOARCH=amd64 go fix $PARAM ./...
GOOS=linux GOARCH=arm64 go fix $PARAM ./...
GOOS=darwin GOARCH=amd64 go fix $PARAM ./...
GOOS=darwin GOARCH=arm64 go fix $PARAM ./...
GOOS=windows GOARCH=amd64 go fix $PARAM ./...
GOOS=windows GOARCH=arm64 go fix $PARAM ./...
