openapi: 3.0.3
info:
  title: Aerospike Cloud Public API
  version: 2.0.0
  description: Public API for the Aerospike Cloud offering
  contact:
    name: Aerospike Cloud
servers:
  - url: https://api.aerospike.cloud/v2
security:
  - publicOauth2: []
tags:
  - name: cloud-provider
    description: |
      APIs which facilitate cloud-provider actions.
  - name: database
    description: |
      APIs which facilitate database management as a service.
  - name: database-credential
    description: |
      APIs which facilitate api-key management.
  - name: notification
    description: |
      APIs which facilitate notification management.
  - name: organization
    description: |
      APIs which facilitate self service organization management
  - name: secret
    description: |
      APIs which facilitate secret management.
  - name: storage-class
    description: |
      APIs which facilitate storage-class actions.
paths:
  /cloud-providers:
    get:
      summary: Get supported cloud providers.
      description: |
        Returns a list of supported cloud providers and regions.
      security:
        - publicOauth2: []
      tags:
        - cloud-provider
      operationId: getCloudProviders
  /cloud-providers/{cloudProviderId}/instance-types/{instanceTypeId}:
    get:
      summary: Get specs for an instance type.
      description: Returns the specs for a given instance type.
      security:
        - publicOauth2: []
      tags:
        - cloud-provider
      operationId: getCloudProviderInstanceTypeSpecs
  /organization:
    get:
      summary: Get your organization
      description: Get your organization
      security:
        - publicOauth2:
            - read:org
      tags:
        - organization
      operationId: getOrganization
  /organization/notifications:
    get:
      summary: Get notifications of your organization
      description: Returns the last 25 notification for an organization.
      security:
        - publicOauth2:
            - read:org
      tags:
        - notification
      operationId: getNotifications
  /organization/notifications/clear:
    post:
      summary: Mark all notifications of your organization as read
      description: Mark all notifications of your organization as read.
      security:
        - publicOauth2:
            - update:org
      tags:
        - notification
      operationId: clearNotifications
  /organization/members:
    get:
      summary: List org members
      description: List members of the organization.
      security:
        - publicOauth2:
            - read:org
      tags:
        - organization
      operationId: listOrgMembers
  /organization/members/{userId}:
    delete:
      summary: Remove org member
      description: Removes a member from the organization.
      security:
        - publicOauth2:
            - update:org
      tags:
        - organization
      operationId: removeOrgMember
  /api-keys:
    get:
      summary: Get all API keys.
      description: Get all API keys.
      security:
        - publicOauth2:
            - read:api-key
      tags:
        - api-key
      operationId: listApiKeys
    post:
      summary: Create a new API key
      description: Create a new API key
      security:
        - publicOauth2:
            - create:api-key
      tags:
        - api-key
      operationId: createApiKey
  /api-keys/{clientId}:
    delete:
      summary: Delete an API key
      description: Delete an API key
      security:
        - publicOauth2:
            - delete:api-key
      tags:
        - api-key
      operationId: deleteApiKey
  /secrets:
    get:
      summary: List all secrets.
      description: Retrieves a list of all secrets accessible to the user
      security:
        - publicOauth2:
            - read:secret
      tags:
        - secret
      operationId: listSecrets
    post:
      summary: Create a new secret
      description: Create a new secret
      security:
        - publicOauth2:
            - create:secret
      tags:
        - secret
      operationId: createSecret
  /secrets/{secretId}:
    get:
      description: Get an existing secret by Id
      security:
        - publicOauth2:
            - read:secret
      tags:
        - secret
      summary: Get an existing secret
      operationId: getSecretById
    delete:
      summary: Delete a secret
      description: Delete a secret.
      security:
        - publicOauth2:
            - delete:secret
      tags:
        - secret
      operationId: deleteSecretById
  /databases:
    get:
      summary: Get all databases.
      description: |-
        Retrieves a list of all databases accessible to the user.
        The list can be filtered by status.
      security:
        - publicOauth2:
            - read:database
      tags:
        - database
      operationId: getDatabases
    post:
      summary: Create a new database
      description: Create a new database
      security:
        - publicOauth2:
            - create:database
      tags:
        - database
      operationId: createDatabase
  /databases/{databaseId}:
    get:
      description: Get an existing database by Id
      security:
        - publicOauth2:
            - read:database
      tags:
        - database
      summary: Get an existing database
      operationId: getDatabaseById
    patch:
      summary: Update an existing database
      description: Update an existing database.
      security:
        - publicOauth2:
            - update:database
      tags:
        - database
      operationId: updateDatabaseById
    delete:
      summary: Delete a database
      description: Delete a database.
      security:
        - publicOauth2:
            - delete:database
      tags:
        - database
      operationId: deleteDatabaseById
  /databases/{databaseId}/metrics:
    get:
      summary: Get database metrics
      description: Returns all metrics for the given database
      security:
        - publicOauth2:
            - read:database
      tags:
        - database
      operationId: getDatabaseMetrics
  /databases/{databaseId}/credentials:
    get:
      summary: Get all credentials for a database
      description: Get all credentials for a databases.
      security:
        - publicOauth2:
            - read:database
      tags:
        - database-credential
      operationId: getDatabaseCredentials
    post:
      summary: Create new credentials for a database
      description: |
        Create a new API key for a database.

        Supports `read`, `write`, `read-write` privileges for CORE databases. Defaults to `read-write`.
      security:
        - publicOauth2:
            - update:database
      tags:
        - database-credential
      operationId: createDatabaseCredentials
  /databases/{databaseId}/credentials/{credentialsId}:
    delete:
      summary: Delete credentials for a database
      description: Deletes credentials for a database.
      security:
        - publicOauth2:
            - update:database
      tags:
        - database-credential
      operationId: deleteCredentialsById
  /databases/{databaseId}/private-access:
  /databases/{databaseId}/private-access/consumers:
  /databases/{databaseId}/private-access/consumers/{consumerId}:
  /databases/{databaseId}/vpc-peerings:
    post:
      summary: Create a single VPC Peering connection for the database
      description: Create a single VPC Peering connection for the database.
      security:
        - publicOauth2:
            - update:database
      tags:
        - database-vpc-peerings
      operationId: createVPCPeerings
    get:
      summary: Get all VPC peering information in the database
      description: Get all VPC peering information in the database
      security:
        - publicOauth2:
            - read:database
      tags:
        - database-vpc-peerings
      operationId: getVPCPeerings
  /databases/{databaseId}/vpc-peerings/{vpcId}:
    delete:
      summary: Delete a VPC peering connection in the database
      description: DDelete a VPC peering connection in the database.
      security:
        - publicOauth2:
            - delete:database
      tags:
        - database-vpc-peerings
      operationId: deleteVPCPeerings
  /topologies:
    post:
      summary: Create Topology
      description: Creates a new XDR topology for managing replication between Aerospike Cloud databases
      operationId: createTopology
      tags:
        - topologies
    get:
      summary: List Topologies
      description: Lists all topologies for the organization
      operationId: listTopologies
      tags:
        - topologies
  /topologies/{topologyId}:
    get:
      summary: Get Topology
      description: Retrieves details of a specific topology
      operationId: getTopology
      tags:
        - topologies
    patch:
      summary: Update Topology
      description: Updates an existing topology configuration
      operationId: updateTopology
      tags:
        - topologies
    delete:
      summary: Delete Topology
      description: Deletes a topology and removes all associated configurations
      operationId: deleteTopology
      tags:
        - topologies
components:
  securitySchemes:
    publicOauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.control.aerospike.cloud/oauth/token
          scopes:
            read:database: Read operations on database resources
            update:database: Update operations on database resources
            create:database: Create operations on database resources
            delete:database: Delete operations on database resources
            read:org: Read operations on org resources
            update:org: Update operations on org resources
            read:api-key: Read operations on environment resources
            create:api-key: Create operations on api key resources
            delete:api-key: Delete operations on api key resources
            read:secret: Read operations on secret resources
            create:secret: Create operations on secret resources
            delete:secret: Delete operations on secret resources
x-cli-config:
  security: publicOauth2
  prompt:
    client_id:
      description: API Key ID
    client_secret:
      description: API Key secret
  params:
    client_id: '{client_id}'
    client_secret: '{client_secret}'
