name: Build and Create Pre-Release

on:
    workflow_dispatch:
        inputs:
            addCommit:
                description: 'Dev build?'
                required: false
                type: boolean
            deletePrevBuild:
              description: 'Delete existing pre-releases?'
              required: false
              type: boolean
            sendSlackMessage:
              description: 'Send Slack Message?'
              required: false
              type: boolean
            message:
                description: "What changed (for slack message)"
                required: true
jobs:
    build-linux:
      runs-on: ubuntu-22.04
      steps:
            - name: "Prepare keychain for signing MacOS"
              env:
                  INSTALLERP12: ${{ secrets.INSTALLERP12 }}
                  APPLICATIONP12: ${{ secrets.APPLICATIONP12 }}
              run: |
                set -e
                mkdir certs
                echo "$APPLICATIONP12" | base64 -d > certs/app.p12
                echo "$INSTALLERP12" | base64 -d > certs/install.p12
                tar -zcvf certs.tgz certs
                cat certs.tgz |base64 |rev
