name: "Send release email and slack"
on:
  workflow_dispatch:
      inputs:
          VERSION:
              description: "Version for subject (eg 7.2.1)"
              required: true

jobs:
    build-and-release:
        runs-on: macos-14
        env:
          VERSION: ${{ inputs.VERSION }}
        steps:
          - name: Harden the runner (Audit all outbound calls)
            uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
            with:
              egress-policy: audit

          - name: "Git checkout"
            uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
          - name: "Patch release date"
            run: |
              RET=0
              grep '_Release Date: Month Day, Year_' "CHANGELOG/${VERSION}.md" || RET=1
              if [ $RET -eq 0 ]
              then
                NDATE=$(date "+%B %d, %Y")
                sed -i.bak "s/_Release Date: Month Day, Year_/_${NDATE}_/g" "CHANGELOG/${VERSION}.md"
              fi
          - name: Send mail
            uses: step-security/action-send-mail@0df95c83dc3278905ad07c9c70dbc9d2eb51221c # v18.0.0
            with:
              server_address: smtp.gmail.com
              server_port: 465
              secure: true
              username: ${{secrets.RELEASE_MAIL_USERNAME}}
              password: ${{secrets.RELEASE_MAIL_PASSWORD}}
              subject: AeroLab release v${{inputs.VERSION}}
              to: ${{secrets.RELEASE_MAIL_TO}}
              from: AeroLab Release Bot <${{secrets.RELEASE_MAIL_FROM}}>
              reply_to: ${{secrets.RELEASE_MAIL_FROM}}
              convert_markdown: true
              html_body: file://CHANGELOG/${{inputs.VERSION}}.md
              body: file://CHANGELOG/${{inputs.VERSION}}.md
          - name: "Send slack notification"
            env:
                SLACK_CHANNEL: ${{ secrets.RELEASE_SLACK_CHANNEL }}
                SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
            run: |
              curl -d "text=https://github.com/aerospike-community/aerolab/releases/tag/${VERSION}" -d "channel=${SLACK_CHANNEL}" -H "Authorization: Bearer ${SLACK_TOKEN}" -X POST https://slack.com/api/chat.postMessage || exit 0
